# Generated by Django 4.2 on 2023-05-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creditTocut',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
