# Generated by Django 4.2 on 2023-05-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_credittocut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creditTocut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
